// <auto-generated />
using System;
using BankMVC.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankMVC.Data.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20201112005058_SqlServerMigration")]
    partial class SqlServerMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BankMVC.Model.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("pin");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("balance");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("TransactionId")
                        .HasName("transaction_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 1000.0,
                            TransactionDate = new DateTime(2020, 11, 12, 1, 50, 57, 923, DateTimeKind.Local).AddTicks(4399),
                            UserName = "user1"
                        },
                        new
                        {
                            TransactionId = 2,
                            Amount = 1000.0,
                            TransactionDate = new DateTime(2020, 11, 12, 1, 50, 57, 927, DateTimeKind.Local).AddTicks(9627),
                            UserName = "user1"
                        },
                        new
                        {
                            TransactionId = 3,
                            Amount = 1000.0,
                            TransactionDate = new DateTime(2020, 11, 12, 1, 50, 57, 927, DateTimeKind.Local).AddTicks(9807),
                            UserName = "user1"
                        });
                });

            modelBuilder.Entity("BankMVC.Model.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Balance")
                        .HasColumnType("float")
                        .HasColumnName("balance");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pin");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId")
                        .HasName("user_pkey");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Balance = 3000.0,
                            Pin = "BCDE",
                            UserName = "user1"
                        });
                });

            modelBuilder.Entity("BankMVC.Model.Models.Transaction", b =>
                {
                    b.HasOne("BankMVC.Model.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankMVC.Model.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
